### ISSUE TITLE
Cannot find type 'AnimationView' in scope

### ISSUE THREAD

**Issue by zhuyifan2013** [jasudev/LottieUI#4]
<img width="965" alt="CleanShot 2022-12-27 at 19 41 33@2x" src="https://user-images.githubusercontent.com/3753079/209661555-9a8284fe-b361-4c22-9761-d1526b09b77e.png">

iOS deployment target: 16.0
pod 'lottie-ios', '4.0.1'

**Comment by jasudev** [comment]
Changes due to Lottie library update, merged into the main branch.
