### ISSUE TITLE
Cannot infer contextual base in reference to member 'loop'

### ISSUE THREAD

**Issue by jacobtimm** [jasudev/LottieUI#6]
I get this error when running this code

struct WaveView: View {
    @State var isPlaying: Bool = true
    
    var body: some View {
        LottieView("wave")
            .play(isPlaying)
            .loopMode(.loop) //Cannot infer contextual base in reference to member 'loop'
        
    }
}

**Comment by jasudev** [comment]
I think you're confusing it with another library. This library only controls via environment variables, so it doesn't control via modifiers. Please see the example app. Thank you.
